# Generated by Django 2.1.7 on 2019-03-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PicGallery',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('imgpath', models.TextField()),
                ('title', models.TextField()),
            ],
        ),
    ]
